### PR TITLE
Support custom collections for ReferenceFields with inheritence, gracefully lookup non-existing references

### PR DESCRIPTION
**Pull request by tremolo**
Allow custom collections for ReferenceFields when objects are assigned that inherit the specified reference class. Before it was not possible to specify a custom collection for any inherited References.

Also gracefully resolve ReferenceFields in ListFields.
If the reference can not be resolved,
for example the reference target was deleted from the database,
issue a UserWarning.

### CODE REVIEW

**Comment by rozza** [comment]
Hi,

I'm not sure if this is already in dev - can you provide a test case?

Cheers,

Ross

**Comment by tremolo** [comment]
I applied the changes to a recent checkout,
which is https://github.com/tremolo/mongoengine/commit/c059ad47f24394c3bb3f4b4f24a6f9e91280c4ab
It does not seem to be addressed in that version.

I will try to prepare a test on the weekend.

Cheers,

Lutz

**Comment by rozza** [comment]
Hi yeah thats still on the master branch.

**Comment by tremolo** [comment]
So which is the most recent version ?
If there is already similar code can you give me a link to the changeset?

**Comment by rozza** [comment]
Hi I'd checkout the dev branch it has the most recent code in and many improvements over master.

https://github.com/hmarr/mongoengine/tree/dev

Its nearing being merged into master.

**Comment by rozza** [comment]
Closing as this is available

**Pull request closed without merging**
