### PR TITLE
Ability to have scalar returns instead of partially-popuated Document instances.

### PR DESCRIPTION
**Pull request by amcgregor**
In my current use case I have one embedded document with a field containing an ID, and two other collections with similar IDs and different names.  I needed to `itertools.chain()` the result of three queries, but only get the desired ID _value_ as a result.  (I also needed to retain the ability to `len()` the queries and not consume all records, so comprehensions were out).

The result is the attached pull request, usable like this:

``` python
from mongoengine import *

connect('foo')

class Bar(EmbeddedDocument):
    age = IntField()

class Foo(Document):
    name = StringField()
    detail = EmbeddedDocumentField(Bar)

Foo.drop_collection()

a = Foo(name="Foo", detail=Bar(age=27)) ; a.save()
b = Foo(name="Bar", detail=Bar(age=30)) ; b.save()
c = Foo(name="Baz", detail=Bar(age=4)) ; c.save()

print list(Foo.objects.scalar('name'))
# ['Foo', 'Bar', 'Baz']
print list(Foo.objects.scalar('detail__age'))
# [27, 30, 4]
print list(Foo.objects.scalar('name', 'detail__age'))
# [('Foo', 27), …]
```

It's a rough implementation (e.g. probably doesn't handle missing values well or at all) but it works quite well for my needs.

### CODE REVIEW

**Comment by amcgregor** [comment]
Thinking about it further, if I could translate the names passed to `scalar` into Field references, I could directly call from_son on them and never instantiate a Document instance at all.

**Comment by rozza** [comment]
Is this similar to #393 @wpjunior created a `.values_list` method for querysets (currently in dev)

**Comment by amcgregor** [comment]
Similar, though mine uses the correct terminology, avoids the use of an underscore, and handles the reference edge cases with 100 fewer lines of change. Mine is substantially simpler; no additional classes needed.

**Comment by amcgregor** [comment]
Tuple vs. list, and in mine a single value isn't even wrapped in anything, it's served straight up.

Also, can't tell from the other requests' code, but mine effects anywhere in the query that Document objects are prepared allowing you to utilize some of the more esoteric features (e.g. return a dict mapping object IDs to objects) while still getting single values or tuples back.

**Comment by amcgregor** [comment]
Mine also retains the ability to further mutate the query after defining which scalar vales you want, e.g. skip/limit, filter, etc.

**Comment by rozza** [comment]
Thanks Alice - great points.

I'll look into merging this into the dev branch and I'll revisit: `values_list`

**Comment by amcgregor** [comment]
@rozza The unit test suite for #393 should work quite well on mine with a few minor name changes and added testing of chaining and the behaviour of `get()`, `first()`, `with_id()`, `in_bulk()`, slicing, and various query mutators (`filter()`, `limit()`, `skip()`, etc.).

**Comment by amcgregor** [comment]
An additional example:

``` python
from mongoengine import *

connect('foo')

class Organization(Document):
    id = ObjectIdField('_id')
    name = StringField()

class User(Document):
    id = ObjectIdField('_id')
    name = StringField()
    organization = ObjectIdField()

User.drop_collection()
Organization.drop_collection()

whitehouse = Organization(name="White House") ; whitehouse.save()
bob = User(name="Bob Dole", organization=whitehouse.id) ; bob.save()

# Efficient way to get all unique organization names for a given set of users.
# (Pretend this has additional filtering.)
orgs = set(User.objects.scalar('organization'))
print list(Organization.objects(id__in=list(orgs)).scalar('name'))

# Efficient for generating listings, too.
orgs = Organization.objects.scalar('name').in_bulk(list(orgs))

for user, org in User.objects.scalar('name', 'organization'):
    print user, orgs[org]

```

**Comment by rozza** [comment]
This is now in the `dev` branch thanks Alice its awesome :)

**Pull request closed without merging**
