### PR TITLE
New field which allows multiple types of data.

### PR DESCRIPTION
**Pull request by tevino**
It may be used like this:

```
class Config(Document):
    name = StringField()
    value = MultiTypeField()
```

The value of one Config can be bool, string, int by default, you can specify what are allowed too.
Hope this can help.
Thanks.

### CODE REVIEW

**Comment by rozza** [comment]
Hi you could use the `DynamicField` that is used by DynamicDocuments - that also handles references and other complex types.

**Comment by tevino** [comment]
docs matters, thanks.

**Comment by rozza** [comment]
Yeah sorry, I only created it for dynamic documents and didnt pause to
think it would be useful outside that context!  Thanks for the ticket Tevin!

On Thu, Jul 12, 2012 at 1:48 AM, Tevin <
reply@reply.github.com

**Comment by tevino** [comment]
That's exactly what I thought!
Thanks for your nice work too rozza!

**Pull request closed without merging**
