### PR TITLE
Update mongoengine/django/tests.py

### PR DESCRIPTION
**Pull request by ghost**
This is my proposition of handling fixtures in MongoTestCase.

### CODE REVIEW

**Comment by rozza** [comment]
This patch needs work.  No import of json, _load_fixtures refers to self but its a static method.

Closing for now - feel free to improve and reopen :)

**Comment by ghost** [comment]
I'v fixed those issues, but i don't have permissions to reopen. Should i create another pull request?

**Comment by rozza** [comment]
Re opened - you can just update your code / branch you based the pull request off.

**Comment by ghost** [comment]
Its already updated.

**Comment by rozza** [comment]
Closing here - will implement in django-mongoengine

**Comment by josephmisiti** [comment]
im late to the game here obviously - but was this ever implemented .... and if so, can someone show me where.
thanks .

**Pull request closed without merging**
