### PR TITLE
Using django and non-django style choices

### PR DESCRIPTION
**Pull request by KarimAllah**

### CODE REVIEW

**Comment by rozza** [comment]
Hi, whats your motivation for reverting back to single choices?

**Comment by KarimAllah** [comment]
Mainly because I'm using single choices a lot in my documents, and this breaks all of it.
Besides, I can't see any value for this django style choices other than being used when you've a view that is represented other than your model and If you don't it'll be just an overhead.

**Comment by rozza** [comment]
@Karim Allah thanks for the ticket, will review as part of the 0.6 release.

**Comment by rozza** [comment]
@KarimAllah - the choices part is now in the dev branch - thanks for the code.

I havent merged in: `Fixing dereferencing when the dereferenced-document wasn't found.`  I wanted to understand more about it - have you got a test case?

**Pull request closed without merging**
