### PR TITLE
add 'to_python' to BaseDoucument

### PR DESCRIPTION
**Pull request by j1anb1n**
this is a very useful function in serialization

### CODE REVIEW

**Comment by rozza** [comment]
looks good - I noticed the fields themselves have a to_python method so you might want to update it to use that

I based this on the to_mongo code:

``` python
 def to_python(self):
    """Return data dictionary of the current document.
    """
    data = {}
    for field_name, field in self._fields.items():
        value = getattr(self, field_name, None)
        if value is not None:
            if hasattr(value, 'to_python'):
                value = value.to_python()
            data[field_name] = value
    # Only add _cls and _types if allow_inheritance is not False
    if not (hasattr(self, '_meta') and
            self._meta.get('allow_inheritance', True) == False):
        data['_cls'] = self._class_name
        data['_types'] = self._superclasses.keys() + [self._class_name]
    if data.has_key('_id') and data['_id'] is None:
        del data['_id']
    return data
```

Also that will recursively call to_python so embedded docs / references should be converted eg:

``` python

class BlogPost(Document):
    content = StringField()
    author = ReferenceField(self.Person)
...

post.to_python()

#Gives:
{
    'content': 'Watched some TV',
     '_types': ['BlogPost'],
     '_cls': 'BlogPost',
     'id': ObjectId('4ddd02ed14d0ff263c000014'),
     'author': {
        '_types': ['Person'],
         '_cls': 'Person',
         'name': 'Test User',
         'id': ObjectId('4ddd02ed14d0ff263c000013')
    }
}
```

Obviously it would need regression tests before being able to be added :)

**Comment by rozza** [comment]
Not sure I like the ObjectId representation as it's not json..

**Comment by rozza** [comment]
@j1anb1n - how do you handle objectId's ?

Any usecases?

**Comment by j1anb1n** [comment]
I just return objectid.**str**()

I write a json_encode_default:

```
def json_encode_default(obj):
    from datetime import datetime, date
    if isinstance(obj, datetime):
        return obj.strftime('%Y-%m-%dT%H:%M:%S')
    elif isinstance(obj, date):
        return obj.strftime('%Y-%m-%d')
    else:
        return obj.__str__()
```

I use it like this:

```
json.dumps(tweet.to_python(), default=json_encode_default)
```

Gives:

``` python
{
    "id": "4de8da651e9aca9961000000",
    "retweeters": [],
    "_types": ["Tweet"], 
    "likers": [], 
    "author": "DBRef(u\'user\', ObjectId(\'4de8c0d01e9aca839300000e\'))", 
    "create_datetime": "2011-06-03T08:15:53", 
    "content": "hello world" 
    "_cls": "Tweet", 
    "replies": [], 
}
```

I don't like DBRef's representation...
I would like this:

``` python
{
    "id": "4de8da651e9aca9961000000",
    #...,
    "author": {
        "collection":  "user",
        "id": "4de8c0d01e9aca839300000e"
    },
    #...
}
```

ps: sorry for my poor English... :)

**Comment by rozza** [comment]
See #210 - I've rescoped this issue so it can make it into the core.

**Pull request closed without merging**
