### PR TITLE
add CalculatedField

### PR DESCRIPTION
**Pull request by tevino**
usage:

```
class Foo(Document):
    begin_time = FloatField()
    end_time = FloatField()
    duration = CalculatedField('_do_subtract')
    _do_subtract(self):
        return self.end_time - self.begin_time
```

Thanks.

### CODE REVIEW

**Comment by rozza** [comment]
Wouldnt a property be better suited?

**Comment by shaunduncan** [comment]
Based on the implementation here, I think you're right that a property would be better suited. However, I could see a benefit in having a field that may be calculated and stored implicitly, which would open the door to being able to index and query the value itself.

**Comment by tevino** [comment]
Property was the very first came to my mind when I was implementing this, but non of the fields isn't a class, I thought a property may break the coordinate then I made it a class.

**Comment by rozza** [comment]
Not sure I get what you mean @Tevino

The problems you may get with this style field is when is the value calculated?  Everytime you save the document?  That isn't great as save causes race conditions - the whole document is rewritten to the database (although mongoengine does try to limit this).  Inserts / Updates would miss this entirely and wouldn't update its value.

Because of this most people put the logic aside and use signals or other application logic to enforce the updating of the value and consciously acknowledge that using updates means that the value isn't necessarily updated.

**Comment by tevino** [comment]
This field is read-only and it will not save the value into the database at all.
The calculation will be done every time the field is accessed.

**Comment by rozza** [comment]
So why is a property bad?

**Comment by tevino** [comment]
It's not so bad.

For users the usage of a property field is so different than the class field, and the name of that property may break the code convention(like: this_is_a_property and ThisIsAClass)

That's what I worried about.

**Comment by rozza** [comment]
@Tevino thanks for the ticket and the conversation about this, its an interesting idea, but I'm not going to add this field type to the core.  The reasons are a property should be used here, as fields are used by the orm as part of the semantics for querying the database.  This could cause confusion for new beginners who expect it to act differently, also from an application perspective there will be little or no difference to using a property for this use case - this is how I deal with the scenario.

However, there should be nothing preventing you from having this field and importing it locally into your model code, if you desire / require this interface.

**Comment by tevino** [comment]
I'm asking for suggestions about the "property or class" problem here, it's not done yet.

Are you saying if the implementation changes into a property, it will not be accepted neither?

**Comment by rozza** [comment]
Its just python so you can attach attributes / helpers / properties to the
class.

Fields are special as they map to the stored data and are used for looking
up / validating data.

With your use case a property is all's that's needed, unless you want to
store data in the db.
On Jul 25, 2012 5:17 PM, "Tevin" <
reply@reply.github.com>
wrote:

**Comment by tevino** [comment]
It will not be included in the result of document.to_json() nor dict(document) if it is just a python property.

**Pull request closed without merging**
