### PR TITLE
Add oneof option to BaseField

### PR DESCRIPTION
**Pull request by linuxnow**
- oneof is an enum-like option needed to easily limit the allowed values in a field
- bump spec version to 0.5.2

### CODE REVIEW

**Comment by rozza** [comment]
Wheres the PIL dependency?

**Comment by linuxnow** [comment]
I thought ImageField was already integrated :) Working ahead of time :p

**Comment by rozza** [comment]
I was going to say!

ImageField will import PIL internally, rather than a the module level - so PIL wont be a requirement for mongoengine only for ImageFields.  Not sure if that helps with the .spec file or not.

**Comment by linuxnow** [comment]
You can't be so specific :)

**Comment by linuxnow** [comment]
I have updated the patch description. This is an easy and important patch to add an enum-like option when defining the document fields.

**Comment by linuxnow** [comment]
Now htat you have integrated ImageField, I have reintroduced the PIL dependency in the spec file

**Comment by linuxnow** [comment]
Please don't forget to have a look at this one, an enum-like filed is a must-have :)

**Comment by linuxnow** [comment]
I have rebased the patch to solve merge errors, it should aplpy cleanly now.
Please give me some feedback, I'm counting on having this feature :)

**Comment by rozza** [comment]
Hi @linuxnow - sorry for the delay will review this morning :)

**Comment by rozza** [comment]
Hmm - seems to replicate choices functionality.

I have a pull request to make choices more flexible: https://github.com/hmarr/mongoengine/pull/284

Would that suit your needs?

**Comment by linuxnow** [comment]
That patch does the same than mine without adding another option, so go ahead with it.
Remember to replace:
 raise ValidationError
with:
 self.error
And you should add it to the documentation, an example would do it :)

**Comment by rozza** [comment]
@linuxnow - all added :)

**Pull request closed without merging**
