### PR TITLE
My try to close #467

### LINKED ISSUE #467: ObjectId as ReferenceField
It would be nice to introduce a new field type RefObjectId(collection) that would act as ReferenceField(), e.g. could be dereferenced and "cascade"s would work to.

### PR DESCRIPTION
**Pull request by danaki**
Have not tested all "recursion" stuff...

### CODE REVIEW

**Comment by rozza** [comment]
I like this - but I may merge it into the ReferenceField and use it as a setting and then default this way as on by default.

The aim there is to make it use the best default possible and allow an upgrade path for people.  I'll push this for 0.7.

**Comment by danaki** [comment]
Harry,

Do I have to re-pull my request to http://github.com/MongoEngine/mongoengine ?
Do I have any chance to see this functionality in 0.7?

In our project we got rid of ReferenceFields by replacing it by ObjectIdFields and do all dereferencing manually when
it's needed, because dereference of N records in N requests is slower than 1 request of N records.

I would like to suggest a way to disable auto-dereference, for example, when I'm prototyping I just want to see all the data in place, but when I work on performance of pre-release I just want to disable all the dereference logic and enable it explicitly if I need to. This way, an access to a reference field, when dereference of this model field is disabled would raise an exception in my tests and I would rewrite this piece of code with performance in mind.

If I explicitly disable the dereference feature, I would collect all ObjectIds and put them to find({'_id': {'$in': list}}) on the referenced model and get all the data in just 1 request. There're could be a way to put those dereferenced models data back to Mongoengine's models results in order to have access to fields without rewriting the majority of code.

**Comment by rozza** [comment]
0.7 is nearly here its now in the master branch.  Disabling dereferencing is something that might come in 0.8 I've added a ticket for it: MongoEngine/mongoengine#82

The auto dereferencing should be more efficient as it dereferences N records in as fewer queries as possible, where as in 0.4 it used to be 1 query per reference.

**Comment by danaki** [comment]
Thanks. I don't know yet how, but if auto-dereferencing might be disabled, there must be choice whether an attempt to access reference field would throw an exception and break the unprepared code or just give a reference object. See #456

**Comment by rozza** [comment]
See: MongoEngine/mongoengine#89

**Comment by rozza** [comment]
Have implemented the ReferenceField as ObjectId strings part and that will become default in 0.8

Still working on the raw data aspects - keep an eye on: MongoEngine/mongoengine#82

Cheers, Ross

**Comment by rozza** [comment]
Commit: MongoEngine/mongoengine@4ffa8d012446df7ce6df09e37802d5ccd6205e6d

**Pull request closed without merging**
