### PR TITLE
The user model needs to allow for more than 30 characters for username.

### PR DESCRIPTION
**Pull request by garrypolley**
I wanted to use the User model out of the box but it does not support using emails very well since it has a max of 30 characters, and it isn't configurable.  I think 50 is plenty, if more are needed then this should be made into a setting.

### CODE REVIEW

**Comment by rozza** [comment]
Hi, that would no longer mirror the django api - see: https://docs.djangoproject.com/en/dev/topics/auth/#users

**Comment by rozza** [comment]
I'll keep open for now as I may update it when I split out the django mongoengine stuff into its own repo.  Although, I'd prefer to mimic django as much as possible for the auth.

**Comment by garrypolley** [comment]
That makes sense to mimic Django, I agree then.  However, if that is going to be the case, then it would be nice if the FutureWarning was not given when I subclass User.

**Comment by rozza** [comment]
Hi, yes will make that so.

**Comment by rozza** [comment]
User is now extendable in master.

**Comment by garrypolley** [comment]
Thanks, much appreciated.

**Pull request closed without merging**
