### PR TITLE
add muti database support.

### PR DESCRIPTION
**Pull request by kulasama**

### CODE REVIEW

**Comment by rozza** [comment]
Hi,  we have a few multi database implementation ideas now.

I'm not sure I can accept this pull request as it removes map reduce - whats the reasoning behind that?

**Comment by kulasama** [comment]
because mapreduce in mongo is not useful at production environment  i think.   just my  personal option.

and why the multi databse implementation is not merge to master?  it is a importance spec on our system development.

**Comment by iapain** [comment]
Your code needs major improvements because it _changed_ some API which is not desired for example `MapReduce` and `is_safe=True` etc. I like the idea how you hooked multidb support but try to minimize impact on existing API, moreover write some docs as well.

**Comment by rozza** [comment]
Multidb support just landed in the dev branch

**Pull request closed without merging**
