### PR TITLE
allow reload()ing selected fields only

### PR DESCRIPTION
**Pull request by dcrosta**
This is useful if your document is large and you only need to reload a subset of it. Comes with a test.

### CODE REVIEW

**Comment by iapain** [comment]
+1 for functionality and your patch look good except one thing `only` is not a good variable name. Try to repatch it with better variable name. Probably `reload_only_fields` is better name.

**Comment by rozza** [comment]
This could easily cause havoc with _changed_fields etc that haven't been saved and may cause unintended side effects...

**Comment by iapain** [comment]
True `_changed_fields` needs to be tracked as well in the patch.

**Comment by dcrosta** [comment]
I'll work on it and submit some new commits. Any particular test cases I should be aware of?

**Comment by rozza** [comment]
Sorry for the delay,  _changed_fields shouldn't be overwritten only the reloaded fields should be removed.

**Pull request closed without merging**
