### PR TITLE
The port is defaulted in to conn_settings, so discard the port since hos...

### PR DESCRIPTION
**Pull request by samuelclay**
...ts_or_uri must be used.

### CODE REVIEW

**Comment by rozza** [comment]
Thanks for the patch - I'm not sure how you're getting a port - for replicaSets you should use the uri style connection string.

**Comment by samuelclay** [comment]
It's being defaulted in at the top of the file, where port=27017. The URI I'm passing in is "db01:27001", but inspecting conn_settings show a port of 27017.

**Comment by samuelclay** [comment]
Also, perhaps it should be a .pop('port', None), just in case? Although the port is guaranteed to be there due to register_connection's port parameter.

**Comment by rozza** [comment]
ah ok - so URI of "mongodb://db01:27001" should have worked.  Have updated to pop(port, None).

**Pull request merged**
