### PR TITLE
Not work if given value is None in some fields

### PR DESCRIPTION
**Pull request by yamaneko1212**
I found that exceptions are thrown when some prepare_query_value() got None.

Is this bug?

### CODE REVIEW

**Comment by rozza** [comment]
@yamaneko1212 thanks for the patch - have you got a test case, so I can replicate / verify the patch.

**Comment by yamaneko1212** [comment]
Hi rozza. Thanks for your reply.

I wrote a simple test to ensure that all fields accept None when required if False.
https://gist.github.com/1385360

When writing the test, i found that ComplexDateTimeField return current time when give None to it.
I don't know whether it is bug or not and I wrote the test by assuming that it's a feature.
Let me know if any problems.

**Comment by rozza** [comment]
None is not valid for most of these fields, by bypassing the preparation you effectively stop the validation - I'm not sure that this is what people would expect.

**Comment by yamaneko1212** [comment]
Sorry, above test is completely wrong, it never call prepare_query_value(). I wrote other test.
https://gist.github.com/1386956
This time, exclude the fields that I don't modify from test.

> None is not valid for most of these fields,

I read BaseDocument, BaseField and API Document and I understood that all fields can accept required option. So that, I guess all fields could have None.

**Comment by tkloc** [comment]
For me, it looks like a bug. I see few things that have to be done. First, this only thow exception on update(), because it's force value validation by using prepare_query_value(). But your patch should contains 'required' check. For example:

```
     def prepare_query_value(self, op, value):
        if not self.required and value is None: 
            return value
        return int(value) # or even some try which raising ValidationError
```

Second thing, is to fix all fields with have custom **set** method, for example ComplexDateTimeField:

```
    def __set__(self, instance, value):
        value = self._convert_from_datetime(value)
        return super(ComplexDateTimeField, self).__set__(instance, value)
```

this also should allow None value if self.required is False

Rozz, am i right?

**Comment by rozza** [comment]
I'm not 100% of the use case to storing None - so could do with more background on what this is trying to active.  

Any field having None would fail validation and you wouldnt be able to save it back, I'm not sure if this is an issue for you or not as again I'm not sure of the particular use case.

**Comment by tkloc** [comment]
Let's look at the IntField. If we defined it with required=False, we should have possibility to set field with no value. 'No value' means None in this case. You could do:

```
(basing on test case)
doc = AllFields()
doc.int_fld = None
doc.save()
```

with no problem, because BaseDocument.validate() checks if field is required:

```
    def validate(self):
        """Ensure that all fields' values are valid and that required fields
        are present.
        """
        # Get a list of tuples of field names and their current values
        fields = [(field, getattr(self, name))
                  for name, field in self._fields.items()]

        # Ensure that each field is matched to a valid value
        for field, value in fields:
            if value is not None:
                try:
                    field._validate(value)
                except (ValueError, AttributeError, AssertionError), e:
                    raise ValidationError('Invalid value for field named "%s" of type "%s": %s'
                                          % (field.name, field.__class__.__name__, value))
            elif field.required:
                raise ValidationError('Field "%s" is required' % field.name)
```

Problem is only update() function, because it has different behavior. update() doesn't validate value, just try to force value to correct type. The main thing is 'None' should be correct value for fields with required=False (default).
Isn't why 'exists' lookup exist?

some example based on yamaneko's test case:

```
In [155]: AllFields.objects.delete()
In [156]: doc = AllFields(int_fld=1)
In [157]: doc.save()
In [158]: AllFields.objects.filter(int_fld__exists=False)
Out[158]: []
In [159]: doc.int_fld = None
In [160]: doc.save()
In [161]: AllFields.objects.filter(int_fld__exists=False)
Out[161]: [<AllFields: AllFields object>]
In [162]: AllFields.objects.all().update(int_fld=None)
ERROR: An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line statement', (152, 0))

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/secure/tomek/projects/.../<ipython-input-162-a1e89ebecb52> in <module>()
----> 1 AllFields.objects.all().update(int_fld=None)

/secure/tomek/projects/.../libs/mongoengine/queryset.pyc in update(self, safe_update, upsert, multi, write_options, **update)
   1306             write_options = {}
   1307 
-> 1308         update = QuerySet._transform_update(self._document, **update)
   1309         try:
   1310             ret = self._collection.update(self._query, update, multi=multi,

/secure/tomek/projects/.../libs/mongoengine/queryset.pyc in _transform_update(cls, _doc_cls, **update)
   1273 
   1274                 if op in (None, 'set', 'push', 'pull', 'addToSet'):
-> 1275                     value = field.prepare_query_value(op, value)
   1276                 elif op in ('pushAll', 'pullAll'):
   1277                     value = [field.prepare_query_value(op, v) for v in value]

/secure/tomek/projects/.../libs/mongoengine/fields.pyc in prepare_query_value(self, op, value)
    154 
    155     def prepare_query_value(self, op, value):
--> 156         return int(value)
    157 
    158 

TypeError: int() argument must be a string or a number, not 'NoneType'
```

**Comment by rozza** [comment]
Ok - whats are the benefits of setting it to None over deleting it from the document?

**Comment by tkloc** [comment]
yes, setting to None and deleting give us same result, but we expect that update(field=None) should behave exactly like 

```
for obj in queryset:
  obj.field = None
  obj.save()
```

(but in a 'bulk way')

.. and what is less important, it's a default django behaviour.

**Comment by rozza** [comment]
Cool - thanks for the explainations

**Comment by rozza** [comment]
Hi guys,

I have created a bug branch see: https://github.com/hmarr/mongoengine/compare/dev...bug/362

Before I merge it into dev any feedback on it?

Ross

**Comment by rozza** [comment]
Also any reason not to allow None data from the database at all (https://github.com/hmarr/mongoengine/compare/dev...bug/362#L2R758)

The document wont be valid but that could be corrected before saving rather than just throwing an error..

**Comment by rozza** [comment]
Have updated - will add another test - to confirm can load then merge into dev

**Comment by rozza** [comment]
@yamaneko1212  @tkloc  - thanks for the feature request and taking time to explain it to me, this is now on the dev branch!

**Comment by yamaneko1212** [comment]
@Rozza thanks for accepting pull request ;)
@tkloc thanks for helping me :)

**Pull request closed without merging**
