### PR TITLE
Fix bug in appendField flag in _transform_query and _transform_update.

### PR DESCRIPTION
**Pull request by tw1nturb0**
This changeset fixes a bug in a flag in the _transform_query and _transform_update methods of QuerySet, which was preventing some inserts of EmbeddedDocuments when using the $ operator in a list update.

The updated unit test will probably explain it more clearly than I can =)

### CODE REVIEW

**Comment by tw1nturb0** [comment]
Oops- just looked at the dev branch and it appears this has already been fixed for _transform_update.  It looks like the same problem may still exist in _transform_query however.

**Comment by rozza** [comment]
No worries @tw1nturb0 I've put this for review for 0.6 so will fix in dev probably tomorrow morning :)

**Comment by rozza** [comment]
I've cleaned up _transform_query - but I couldnt reproduce / create a test case to prove it broken - but it makes sense to keep it clean.  The actual issue was fixed in #354 and is in dev :)

**Comment by tw1nturb0** [comment]
Thanks!  I'll be sure to check the dev branch before I try to fix any issues I find going forward =)

**Comment by rozza** [comment]
0.6 should be out soon!

On Fri, Dec 2, 2011 at 2:49 PM, tw1nturb0 <
reply@reply.github.com

**Pull request closed without merging**
