### PR TITLE
Don't allow empty lists when they are required

### PR DESCRIPTION
**Pull request by linuxnow**
This patch forces ListField not to be empty when marked as required.
There is a small patch too that adds some more files to .gitignore.

### CODE REVIEW

**Comment by rozza** [comment]
Not 100% sure on this ticket: see #74

It is a valid list, its just empty..

**Comment by linuxnow** [comment]
I've read ticket #74 and I agree with this:
@hmarr: "I'm reluctant to always store no value when a blank string is provided as some people would want to make a distinction between nothing and an empty string, however I do appreciate your point and reckon that something should be done about it."
You might want to distinguish between None and empty (we'd say NULL and empty in relational DB terms).

In the case of the FieldList, it defaults to an empty list and it is stored like that. Currently the required attribute is not used in ListField, but it's not allowed to assign it a None value.

My proposal is to use the required attribute to enforce that the list is not empty, IMHO it does not make sense to add the required attribute to check whether there is a list or not as this is already the behaviour without required, ListField fields are always stored.

Why would you want to validate an empty list and make it required when this is the default behaviour (and can't be changed as you cannot assign None)?

**Comment by rozza** [comment]
Good points, I forgot that ComplexFields default to empty lists / dict and arent stored as null values.

Have changed it so both listfields and dictfields are validated correctly and updated the docs.

Thanks again @linuxnow

**Comment by linuxnow** [comment]
Great!

**Pull request merged**
