### PR TITLE
within_polygon

### PR DESCRIPTION
**Pull request by johnarnfield**
Hi Harry,

I'm new to mongodb, so please forgive my ignorance if there's a reason this wasn't already in :)

I've added "within_polygon" to the geo_operators in queryset.py

### CODE REVIEW

**Comment by rozza** [comment]
Hi,

Thanks for the patch, we'd need a regression test as well.  Also, best to patch against dev branch :)

**Comment by rozza** [comment]
I'm happy to write the test and merge it into dev :)

**Comment by rozza** [comment]
Ah - 1.9 isn't out yet - will probably wait until mongoengine 0.5 is out before adding.

**Comment by johnarnfield** [comment]
rozza, I've updated dev and opened a new pull request: https://github.com/hmarr/mongoengine/pull/263

**Pull request closed without merging**
