### PR TITLE
Reverse ordering for SortedListField

### PR DESCRIPTION
**Pull request by hownowstephen**
Added param 'reverse' for SortedListFields to allow collections to be sorted in descending order instead of the default ascending.

### CODE REVIEW

**Comment by rozza** [comment]
Hi @stephenyoung - thanks for the patch.  Whats your use case for this?  Also can you provide a testcase?

**Comment by hownowstephen** [comment]
I'm using capped collections for managing lists of top occurrences of various datapoints, and need them to be sorted from most to least occurrence - to simplify dealing with data output, it makes more sense to store the data in descending order instead of having to sort afterwards.

**Comment by rozza** [comment]
ok thanks I will look into the patch.

Not sure if this will cause issues with delta'ing / saving could
potentially be some pitfalls there.

Ross

On Tue, Nov 22, 2011 at 3:17 PM, Stephen Young <
reply@reply.github.com

**Comment by hownowstephen** [comment]
Thanks! I'm using my version in an application I'm developing and will let you know if I come across any issues it causes.

**Comment by rozza** [comment]
Thanks @stephenyoung - added it to the dev branch

**Pull request closed without merging**
