### PR TITLE
db_alias using in model, queryset, reference fields, derefrence.

### PR DESCRIPTION
**Pull request by Ankhbayar**
One idea for multi database support. 

Please discuss.

### CODE REVIEW

**Comment by wpjunior** [comment]
+1, very good :-)

**Comment by rozza** [comment]
@Ankhbayar - it looks good, I will clean up and rebase this patch and add docs but looks good.

**Comment by rozza** [comment]
Cleaned up and added docs: e7bcb5e3665d42f46f7ce8e73dcd40d6fb3b7c20

**Comment by rozza** [comment]
@Ankhbayar - this is now in the dev branch - thanks for the code!

**Comment by Ankhbayar** [comment]
WoW. Thanks.

**Pull request closed without merging**
